services:
  frontend:
    build:
      context: ./vite-react-test/vite-project
    ports:
      - "3000:3000"  # Exposes the frontend on localhost:3000
    depends_on:
      - backend


  backend:
    build:
      context: ./docker-compose-fullstack/backend
    ports:
      - "8000:8000"  # Exposes the backend on localhost:8000
    env_file:
    - docker-compose-fullstack/backend/.env
