services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Exposes the frontend on localhost:3000
    depends_on:
      - backend


  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Exposes the backend on localhost:8000
    env_file:
    - backend/.env
